# Generated by Django 4.2.25 on 2026-05-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="teachers/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not shown publicly)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("festival_key", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                (
                    "role_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional override of the team/instagram-handle line shown under the name.",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearances",
                        to="content.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["festival_key", "year", "order"],
                        name="content_tea_festiva_6960f7_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="teacherappearance",
            constraint=models.UniqueConstraint(
                fields=("teacher", "festival_key", "year"),
                name="unique_teacher_per_festival_year",
            ),
        ),
    ]
