# Generated by Django 2.0.5 on 2019-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("booking", "0002_auto_20180603_0914")]

    operations = [
        migrations.CreateModel(
            name="UrbanAcroBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=120)),
                ("numero", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                ("option", models.CharField(blank=True, max_length=20, null=True)),
                ("comment", models.CharField(blank=True, max_length=300, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN", "Informed"),
                            ("CA", "Canceled"),
                            ("PA", "Paid"),
                            ("PE", "Pending"),
                            ("SW", "Switched"),
                            ("WL", "Waiting List"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("pay_till", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WinterAcroBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=250)),
                ("numero", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=250)),
                ("option", models.CharField(max_length=5)),
                ("allergies", models.CharField(max_length=300)),
                ("amount", models.CharField(blank=True, max_length=10, null=True)),
                ("pay_till", models.DateField(blank=True, null=True)),
                ("pay_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN", "Informed"),
                            ("CA", "Canceled"),
                            ("PA", "Paid"),
                            ("PE", "Pending"),
                            ("SW", "Switched"),
                            ("WL", "Waiting List"),
                        ],
                        default="PE",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(name="Booking"),
    ]
