# Generated by Django 2.0.5 on 2019-10-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190613_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urbanacrobooking',
            old_name='numero',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='winteracrobooking',
            old_name='numero',
            new_name='phone',
        ),
    ]
