# Generated by Django 2.0.5 on 2019-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20191011_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='winteracrobooking',
            name='donation',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
