# Generated by Django 2.0.5 on 2018-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_fest_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fest',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fest',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fest',
            name='pay_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fest',
            name='status',
            field=models.CharField(blank=True, choices=[('IN', 'Informed'), ('CA', 'Canceled'), ('PA', 'Payed'), ('PE', 'Pending'), ('SW', 'Switched')], default='PE', max_length=15, null=True),
        ),
    ]
