# Generated by Django 2.0.5 on 2019-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20181015_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fest',
            name='status',
            field=models.CharField(blank=True, choices=[('IN', 'Informed'), ('CA', 'Canceled'), ('PA', 'Paid'), ('PE', 'Pending'), ('SW', 'Switched'), ('WL', 'Waiting List')], default='PE', max_length=15, null=True),
        ),
    ]
