# Generated by Django 2.0.13 on 2019-12-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winteracro', '0002_auto_20191216_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrie',
            name='time',
            field=models.TimeField(),
        ),
    ]
