# Generated by Django 4.2.17 on 2024-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winteracro", "0003_auto_20191222_2322"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="teachers/%Y/")),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order of appearance"),
                ),
                ("active", models.BooleanField(default=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("specialties", models.CharField(blank=True, max_length=200)),
                (
                    "year",
                    models.IntegerField(help_text="Year teaching at the festival"),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
