# Generated by Django 2.0.5 on 2018-10-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0004_auto_20181004_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrie',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fest.Day'),
        ),
    ]
