# Generated by Django 2.0.5 on 2018-10-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0006_auto_20181004_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='entrie',
        ),
        migrations.AddField(
            model_name='entrie',
            name='when',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fest.Day'),
            preserve_default=False,
        ),
    ]
