# Generated by Django 2.0.5 on 2018-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0007_auto_20181004_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrie',
            name='icon',
            field=models.CharField(choices=[('icon fa-home', 'Home'), ('icon fa-flag-checkered', 'Flag'), ('icon fa-fire', 'Fire'), ('icon fa-utensils', 'Cutlery'), ('icon fa-cogs', 'Cogs'), ('icon fa-om', 'Om'), ('icon fa-snowflake', 'Snow'), ('icon fa-magic', 'Magic')], max_length=25),
        ),
    ]
