winter_accomodation_address: Chasa Tschlin, Curtins 6, 7559 Tschlin
winter_accomodation_address_url: https://maps.app.goo.gl/LXpcALwMfqhxdJvXA
winter_accomodation_description: This year we have different sleeping options for
  you. They are distributed into two facilities, all within 2 minutes of the training
  hall.
winter_accomodation_dorms: "<b>Double rooms</b> <br>\r\nAccommodation in spacious\
  \ rooms with 2 beds (together or separated). This option costs you a bit more but\
  \ you'll have gueranteed good sleep and some privacy :-) Mattresses, pillows/comfy\
  \ blankets & covers included. There are spacious and well-maintained sanitary facilities\
  \ with shower/toilet cubicles in the corridor and through the whole buildings. <br>Price:\
  \ 755 CHF per person\r\n<br><br>\r\n<b>Dormitories 3 people</b><br>\r\nRight in\
  \ the house of the training hall. Mattresses, pillows/comfy blankets & covers included.\
  \ Shared bathrooms and showers.\r\n<br>Price: 730 CHF per person\r\n<br><br>\r\n\
  <b>Dormitories 4 people</b><br>\r\nRight in the house of the training hall. Mattresses,\
  \ pillows/comfy blankets & covers included. Shared bathrooms and showers.\r\n<br>Price:\
  \ 705 CHF per person\r\n<br><br>\r\n<b>Dormitories 6 people</b><br>\r\nRight in\
  \ the house of the training hall. Mattresses, pillows/comfy blankets & covers included.\
  \ Shared bathrooms and showers.<br>\r\nPrice: 680 CHF per person<br><br>\r\n\r\n\
  <b>No Accomodation</b> <br>\r\nThere is space for a few vans to park in front of\
  \ the hall. \r\nReach out if you want a no-accomodation option, as there are limited\
  \ slots only.  <br>Price: 500 CHF per person\r\n<br><br>\r\n\r\n<b>Extra Info</b>\
  \ <br>\r\nWe'll place a sauna in front of the hall, facing some beautiful mountains.\
  \ <br>There are free parking places for cars right outside Tschlin, 5 minutes walk\
  \ to the hall. We recommend you to come by train and bus, as there can be a lot\
  \ of snow in that season of the year. If you decide to come by car, make sure to\
  \ bring some snow chains for the wheels.\r\n\r\n<br> Bring some house shoes for\
  \ the hall and house. All the meals are in the main hall. \r\n"
winter_accomodation_dorms_url: https://maps.app.goo.gl/LXpcALwMfqhxdJvXA
winter_accomodation_extra: "We'll place a sauna in front of the hall, facing some\
  \ beautiful mountains. <br>There are free parking places for cars right outside\
  \ Tschlin, 5 minutes walk to the hall. We recommend you to come by train and bus,\
  \ as there can be a lot of snow in that season of the year. If you decide to come\
  \ by car, make sure to bring some snow chains for the wheels.\r\n\r\n<br> Bring\
  \ some house shoes for the hall and house. All the meals are in the main hall. \r\
  \n\r\n"
winter_accomodation_hall_url: https://maps.app.goo.gl/wFy8K6gaSt7ojHde6
winter_accomodation_title: 2026 Sleeping Options
winter_accomodation_title_dorms: 🌄 <b>Get some good sleep in comfy beds!</b>
winter_accomodation_title_upgrade1: 🏘️ <b>Pfadiheim, Arosa</b>
winter_accomodation_title_upgrade2: 🏫 <b>The Training Hall, Arosa</b>
winter_accomodation_upgrade1: "This location offers the benefit of being private,\
  \ but close to our training location. It's 5 minutes walk from the hall, close to\
  \ nature. The Pfadiheim Arosa has a cozy interior and big dormitories for people\
  \ that want to be away from the hall at night, but still in walking distance, to\
  \ be more flexible with their schedule. You don't mind to sleep with 11-13 other\
  \ people in one room? Or you're a group and want to come together into one of the\
  \ two rooms avaliable? Then this might be your best option.\r\n<br><br>\r\n<b>Dormitory\
  \ 12-14 people</b>\r\n      There are mattresses, pillows and blankets. Shared bathrooms\
  \ and showers. Two rooms avaliable.<Br>Price: 820 CHF per person<br>\r\n<br>\r\n"
winter_accomodation_upgrade1_url: https://maps.app.goo.gl/wFy8K6gaSt7ojHde6
winter_accomodation_upgrade2: "The training space offers enough room for some people\
  \ to sleep there as well. If you choose that option, you'll need to bring a sleeping\
  \ bag and pillow with you. We have military mattresses in case you prefer that to\
  \ your own mat or want to travel light. Perfect for the acro addicts that want to\
  \ train until late or people on a budget. We will do our best to make it cosy! Be\
  \ aware that noise might be a factor to deal with.\r\n<br>\r\nPrice: 730 CHF per\
  \ person\r\n<br><br>\r\n"
winter_acro_header_location: <h2><b>Winter Acro Tschlin</b></h2>
winter_general_date: 2. March - 7. March  2026
winter_general_fb: https://www.facebook.com/events/684181852070040/
winter_general_title: 8th Winter Acro Festival
winter_general_whatsapp: <a href="https://chat.whatsapp.com/HFTYA44B5GmJljVFb7vwLG">Winteracro2024</a>
winter_hall_address_url: https://maps.app.goo.gl/LXpcALwMfqhxdJvXA
winter_hall_description: "The beautifully renovated wooden Hall with a little stage\
  \ will be our training space for a week. Lunch and dinner will be served here for\
  \ all participants, creating a central space for both practice and socializing.<br><br>\r\
  \nParking options are available just a 5-minute walk away, right in the entry to\
  \ the little mountain town Tschlin.<br><br>\r\nThe hall is equipped with showers\
  \ and changing rooms, available for use at any time.\r\n"
winter_hall_spa: The hall will be equipped with a sauna. The maintenance will be organized
  through helping tasks and adjusted according to our needs.
winter_hall_spa_description: The hall will be equipped with a sauna. The maintenance
  will be organized through helping tasks and adjusted according to our needs.
winter_hall_title: Turnhalle Tschlin
winter_home_accomodation: "This year we have different sleeping options for you. They\
  \ are distributed into two facilities within 2 walking minutes of the hall:<br>\r\
  \n<br>- Main House <br>\r\n<br>- Macun House<br>\r\n<br>\r\nCheck the price differences\
  \ at \"Prices\".\r\n<br>More important details: <br><br>\r\n"
winter_home_food: "<i>\"We are what we eat\"</i><br>\r\nMain dishes, healthy snacks\
  \ and desserts are<strong> all organic, (mostly) local, vegan and cooked with love</strong>.<br>\
  \ \r\n*<b>Everyone will be asked to colaborate by doing 2 tasks in the kitchen during\
  \ the festival.</b> <br>\r\nKitchen Team: Rosy and her sous chef(fe)s under Mira's\
  \ supervision! <br>\r\n  <br>\r\n"
winter_home_hall: "The beautifully renovated wooden Hall with a little stage will\
  \ be our training space for a week. Lunch and dinner will be served here for all\
  \ participants, creating a central space for both practice and socializing.<br><br>\r\
  \nParking options are available just a 5-minute walk away, right in the entry to\
  \ the little mountain town Tschlin.<br><br>\r\nThe hall is equipped with showers\
  \ and changing rooms, available for use at any time.\r\n"
winter_home_intro: "We're back—and this time, Winter Acro is making a return to the\
  \ cozy corner!\r\n\r\n<br><br> While we loved the site of last year's edition (and\
  \ definitely plan to bring something like that again in the future), we adapted\
  \ this year's edition to our recent private situation of having a son. Like always\
  \ you can count on many of our favorite acrobatics teachers and friends from all\
  \ over the world gathered in one spot!\r\n\r\n<br><br> Expect a week of high-level\
  \ partner acrobatics, Icarian, Acroyoga and dynamic acrobatics workshops in beautiful\
  \ Arosa. With awesome food,  the snow, and the sun, we're going to have so much\
  \ fun this year, and we hope to see many of you for the 8th edition of the Winter\
  \ Acro Festival!\r\n"
winter_home_location: "Arosa is located in the Plessur Range of the Swiss Alps, within\
  \ the canton of Graubünden. The area is known for its scenic alpine landscapes and\
  \ is surrounded by peaks like the Weisshorn (2,653 meters) and Parpaner Rothorn\
  \ (2,861 meters), making it a popular destination for skiing, hiking, and other\
  \ mountain activities. A complete description on how to get there can be found in\
  \ the following link: <br> <br>\r\n"
winter_home_prices: "All tickets include:<br><br>- Accomodation in one of the three\
  \ locations <br>- Food <br> - Workshops <br>- Sauna <br>- Mountain lift ticket for\
  \ the Skiday<br><br>\r\n<strong>Conditions, details and prices:</strong><br> <br>\r\
  \n"
winter_home_sauna: "Beaten up from the daily training?<br><br>Daily sauna under the\
  \ stars! <br>\r\nThere is also a nice natural Iceplunge and Sauna in Arosa that\
  \ you could visit after the Snow Day. <br>\r\nThere will be one sauna at the hall\
  \ and one at house Strela.<br>\r\n"
winter_home_schedule: "DON'T MISS THE OPENING!\r\n<br><br>\r\nEVERYDAY: Sauna after\
  \ dinner  and  jam till late late ;)\r\n"
winter_home_show: "With the help of our teachers and professional artists the show\
  \ is on! But the show is open for you to participate too!! We'd love you to be there\
  \ and share whatever skill you bring! <br> We will share invitations for the event\
  \ to the town of Arosa. Its a big event and we want to celebrate it with you all!\r\
  \n"
winter_home_specialevent: "On Thursday morning we will organize a snow event up on\
  \ the mountain of the Arosa ski resort (If the weather is good). <br>The transportation\
  \ to the station is 10min walk or 2min bus ride (free). <br>  \U0001F642<br>Bring\
  \ warm clothes for outdoor acro. Free afternoon for ski, snowboard or free floor\
  \ at the hall.<br><br>*As an EXTRA, we could organize ski tickets for you, write\
  \ us ;).\r\n"
winter_home_workshops: "There will be <b>3 rounds of 3 acro workshops per \"acro\"\
  \ day</b>. Expect daily handstand, coaching, morning banquine, and other projects\
  \ with plenty of space to jam throughout the day. <b>Longes and mats will be available\
  \ for continuous practice</b>.<br>\r\n<b>Skill Levels</b>:\r\nNo beginner workshops—previous\
  \ acro experience is required.\r\nWorkshops level starts at intermediate with intro-level\
  \ prerequisites for Flows, Icarians, or Standing Acro.\r\n"
winter_prices_description: "Creating an Event like the Winter Acro is a real Orga\
  \ challenge in many ways - but we love the challenge - and we do all we can to keep\
  \ it as accessible as we can, while still offering all the goodies that make this\
  \ event special.\r\n<br>\r\n<strong> All tickets include: food, workshops, wellness\
  \ and snow days ticket.</strong> \r\n<br>\r\nTickets with Accommodation in other\
  \ town then the Hall include the shuttle. Some tickets go without accommodation\
  \ but are limited.<br> There are no single day tickets this year, we want everyone\
  \ to have a full experience of the program we so carefully organized.<br> <br>\r\
  \n<strong>First round of booking confirmations:<br>\r\n10 November 2024</strong><br>\
  \ <br>\r\n<strong>  Confirmation conditions:  </strong> <br>\r\nYour spot is confirmed\
  \ after payment. <br><br>\r\n    <b>Ticket Transfer</b>: You can suggest a transfer\
  \ of your ticket by email, it will strongly be considered - specially in thigh schedule\
  \ - but if there is a waiting list we keep the right to give it preference.<br><br>\r\
  \n\r\n<h2><b>1 CHF = 1€</b></h2><b>To make it easier for our European friends please\
  \ consider 1 CHF = 1€ </b><br>\r\n"
winter_prices_full: '8 Days Pass: CHF 730.- per Person in Aula or Hall'
winter_prices_full_nosleep: '8 Days Pass: CHF 580.- per Person <b>without</b> Accommodation'
winter_prices_refunds: "<strong>Cancellation Policy - In case <u>you</u> cancel.</strong><br>\r\
  \nIn case of cancellation, the following costs are charged: <br>: \r\nUp to 30 days\
  \ prior to the event: CHF 90.- fixed cost <br>\r\n30 to 15 days prior to the event:\
  \  50% Festival Ticket <br>\r\n14 to 1 day(s) prior to the event: 100%  Festival\
  \ Ticket <br>\r\non the day of the Event or no-show:  100%  Festival Ticket<br><br>\
  \ \r\n\r\nIf you cannot join the event but have paid, consider the Ticket transfer\
  \ but let us know asap.<br><br>\r\n\r\n<strong>Cancellation Policy - In case <u>we</u>\
  \ cancel.</strong> <br>\r\nIf we have to cancel the Event there are different conditions\
  \ depending on your booking.<br>\r\n<strong> a)  </strong> without accommodation:\r\
  \nWe are going to <strong> make a full refund</strong>.<br>\r\n<strong> b) </strong>\
  \ with accommodation in Dorms: Fixed fee CHF 90.-  per Person (non-refundable) <br>\
  \ <br>"
winter_prices_short: '<b>NEW 6 Days Pass </b>House Strela Langwies: CHF 650.- Double
  Room, CHF 625.- Dorm 4er , CHF 600.- Dorm 6er; per Person.'
winter_prices_single: '8 Days Pass House Strela Langwies: CHF 870.- Double Room, CHF
  835.- Dorm 4er , CHF 800.- Dorm 6er; per Person.'
winter_prices_upgrade1: '8 Days Pass Pfadiheim Arosa: CHF 820.- per Person in 10er
  Room'
winter_prices_upgrade2: "<strong>No day passes available this year</strong><br><br>\r\
  \n<strong>Price reduction: </strong> <br>\r\n-You can apply for a Helper Ticket.\
  \ (30% reduction on the regular Festival Ticket)<br>\r\n-You can apply to teach\
  \ a Workshop at the Festival (Payout: CHF 70.- per Teacher/Workshop)<br><br>\r\n"
winter_transportation_car: "<p>Once you arrive in Zürich, continue on the A3 motorway\
  \ heading towards Chur. After reaching Landquart, switch to route 28, which leads\
  \ you directly to Arosa. The drive takes you along a stunning alpine route, winding\
  \ through picturesque mountain scenery. After leaving the motorway, the road becomes\
  \ steeper and more serpentine as you begin the climb up to Arosa, with 365 hairpin\
  \ bends and breathtaking views along the way. Be mindful of the weather, especially\
  \ in winter—snow chains or a 4x4 vehicle might be necessary if the roads are icy.\
  \ The ascent is part of the adventure, and once you reach Arosa, the panoramic alpine\
  \ beauty makes it all worthwhile!</p>\r\n"
winter_transportation_car_time: "<ul>\r\n<li>Berne – Arosa: 3h 15min</li>\r\n<li>Basel\
  \ – Arosa: 3h</li>\r\n<li>Geneva – Arosa: 5h</li>\r\n<li>Zurich – Arosa: 2h</li>\r\
  \n</ul>\r\n"
winter_transportation_tickets: <p>Tickets can be bought in the Swiss Main Trains system,
  but it's worth to check other options.</p>
winter_transportation_train: "<p>\r\nThe picturesque destination Arosa is nestled\
  \ in the Swiss Alps at an altitude of 1,800 meters. To reach this charming spot,\
  \ travelers from the North can follow the scenic train route through Switzerland\
  \ (via Landquart, Chur, and on to Arosa). Alternatively, for those coming through\
  \ Austria, the journey can start with the Bratislava train (passing through Landeck-Zams,\
  \ then crossing the border into Switzerland before continuing to Arosa). Both options\
  \ offer stunning alpine landscapes and an unforgettable travel experience.</p>\r\
  \n"
winter_transportation_train_time: "<ul>\r\n<li>Zurich – Chur - Arosa: 2h 30min</li>\r\
  \n<li>Basel - Chur - Arosa: 4h</li>\r\n<li>Geneva – Zürich – Chur – Arosa: 6h </li>\r\
  \n<li>Berne – Zürich - Chur - Arosa: 4h</li>\r\n</ul>\r\n"
