winter_accomodation_address: Chasa Tschlin, Curtins 6, 7559 Tschlin
winter_accomodation_address_url: https://maps.app.goo.gl/LXpcALwMfqhxdJvXA
winter_accomodation_description: This year we have different sleeping options for
  you. They are distributed into two facilities, all within 2 minutes of the training
  hall.
winter_accomodation_dorms: "<b>Double rooms</b> <br>\r\nAccommodation in spacious\
  \ rooms with 2 beds (together or separated). This option costs you a bit more but\
  \ you'll have gueranteed good sleep and some privacy :-) Mattresses, pillows/comfy\
  \ blankets & covers included. There are spacious and well-maintained sanitary facilities\
  \ with shower/toilet cubicles in the corridor and through the whole buildings. <br>Price:\
  \ 755 CHF per person\r\n<br><br>\r\n<b>Dormitories 3 people</b><br>\r\nRight in\
  \ the house of the training hall. Mattresses, pillows/comfy blankets & covers included.\
  \ Shared bathrooms and showers.\r\n<br>Price: 730 CHF per person\r\n<br><br>\r\n\
  <b>Dormitories 4 people</b><br>\r\nRight in the house of the training hall. Mattresses,\
  \ pillows/comfy blankets & covers included. Shared bathrooms and showers.\r\n<br>Price:\
  \ 705 CHF per person\r\n<br><br>\r\n<b>Dormitories 6 people</b><br>\r\nRight in\
  \ the house of the training hall. Mattresses, pillows/comfy blankets & covers included.\
  \ Shared bathrooms and showers.<br>\r\nPrice: 680 CHF per person<br><br>\r\n\r\n\
  <b>No Accomodation</b> <br>\r\nThere is space for a few vans to park in front of\
  \ the hall. \r\nReach out if you want a no-accomodation option, as there are limited\
  \ slots only.  <br>Price: 500 CHF per person\r\n<br><br>\r\n\r\n<b>Early Arrival/\
  \ Late Departure</b> <br>\r\nIf you wnat to make the most of the experience or just\
  \ don't like the train connections, it is possible to arrive on the 1st of March\
  \ and/or depart on the 8th of March. We will charge a minimal price for the bed\
  \ and there will be no food provided, but there's a restaurant in the house too!\
  \ Please reach out to us if you want to make use of that, limited spots only.\r\n\
  \r\n<b>Extra Info</b> <br>\r\nWe'll place a sauna in front of the hall, facing some\
  \ beautiful mountains. <br>There are free parking places for cars right outside\
  \ Tschlin, 5 minutes walk to the hall. We recommend you to come by train and bus,\
  \ as there can be a lot of snow in that season of the year. If you decide to come\
  \ by car, make sure to bring some snow chains for the wheels.\r\n\r\n<br> Bring\
  \ some house shoes for the hall and house. All the meals are in the main hall. \r\
  \n"
winter_accomodation_dorms_url: https://maps.app.goo.gl/LXpcALwMfqhxdJvXA
winter_accomodation_extra: ''
winter_accomodation_hall_url: https://maps.app.goo.gl/wFy8K6gaSt7ojHde6
winter_accomodation_title: 2026 Sleeping Options
winter_accomodation_title_dorms: 🌄 <b>Get some good sleep in comfy beds!</b>
winter_accomodation_title_upgrade1: ''
winter_accomodation_title_upgrade2: ''
winter_accomodation_upgrade1: ''
winter_accomodation_upgrade1_url: ''
winter_accomodation_upgrade2: ''
winter_acro_header_location: <h2><b>Winter Acro Tschlin</b></h2>
winter_general_date: 2. March - 7. March  2026
winter_general_fb: https://www.facebook.com/events/684181852070040/
winter_general_title: 8th Winter Acro Festival
winter_general_whatsapp: <a href="https://chat.whatsapp.com/HFTYA44B5GmJljVFb7vwLG">Winteracro2024</a>
winter_hall_address_url: https://maps.app.goo.gl/LXpcALwMfqhxdJvXA
winter_hall_description: "The beautifully renovated wooden Hall with a little stage\
  \ will be our training space for a week. Lunch and dinner will be served here for\
  \ all participants, creating a central space for both practice and socializing.<br><br>\r\
  \nParking options are available just a 5-minute walk away, right in the entry to\
  \ the little mountain town Tschlin.<br><br>\r\nThe hall is equipped with showers\
  \ and changing rooms, available for use at any time.\r\n"
winter_hall_spa: ''
winter_hall_spa_description: The hall will be equipped with a sauna. The maintenance
  will be organized through helping tasks and adjusted according to our needs.
winter_hall_title: Turnhalle Tschlin
winter_home_accomodation: "This year we have different sleeping options for you. They\
  \ are distributed into two facilities within 2 walking minutes of the hall:<br>\r\
  \n<br>- Main House <br>\r\n<br>- Macun House<br>\r\n<br>\r\nCheck the price differences\
  \ at \"Prices\".\r\n<br>More important details: <br><br>\r\n"
winter_home_food: "<i>\"We are what we eat\"</i><br>\r\nMain dishes, healthy snacks\
  \ and desserts are<strong> all organic, (mostly) local, vegan and cooked with love</strong>.<br>\
  \ \r\n*<b>Everyone will be asked to colaborate by doing 2 tasks in the kitchen during\
  \ the festival.</b> <br>\r\nKitchen Team: Rosy and her sous chef(fe)s under Mira's\
  \ supervision! <br>\r\n  <br>\r\n"
winter_home_hall: "The beautifully renovated wooden Hall with a little stage will\
  \ be our training space for a week. Lunch and dinner will be served here for all\
  \ participants, creating a central space for both practice and socializing.<br><br>\r\
  \nParking options are available just a 5-minute walk away, right in the entry to\
  \ the little mountain town Tschlin.<br><br>\r\nThe hall is equipped with showers\
  \ and changing rooms, available for use at any time.\r\n"
winter_home_intro: "We're back—and this time, Winter Acro is making a return to the\
  \ cozy corner!\r\n\r\n<br><br> While we loved the site of last year's edition (and\
  \ definitely plan to bring something like that again in the future), we adapted\
  \ this year's edition to our recent private situation of having a son. Like always\
  \ you can count on many of our favorite acrobatics teachers and friends from all\
  \ over the world gathered in one spot!\r\n\r\n<br><br> Expect a week of high-level\
  \ partner acrobatics, Icarian, Acroyoga and dynamic acrobatics workshops in beautiful\
  \ Tschlin. With awesome food,  the snow, and the sun, we're going to have so much\
  \ fun this year, and we hope to see many of you for the 8th edition of the Winter\
  \ Acro Festival!\r\n"
winter_home_location: "Tschlin is a traditional mountain village in the Lower Engadin\
  \ valley of the canton of Graubünden, located near the Austrian border. At around\
  \ 1,550 meters above sea level, it offers panoramic views over the Inn valley and\
  \ surrounding alpine peaks. The area is known for its well-preserved Engadin architecture,\
  \ peaceful atmosphere, and access to scenic hiking and biking trails. The Ski area\
  \ \"Scuol\" is only a 20min drive away. A complete description on how to get there\
  \ can be found in the following link: <br> <br>\r\n"
winter_home_prices: "All tickets (except no-accomodation) include:<br><br>- Accomodation\
  \ & bedding <br>- Food & Snacks<br> - Workshops <br>- Sauna <br>- Mountain lift\
  \ ticket for the Skiday<br><br>\r\n<strong>Conditions, details and prices:</strong><br>\
  \ <br>\r\n"
winter_home_sauna: "Beaten up from the daily training?<br>Daily sauna under the stars!\
  \ <br>\r\n<br>\r\n"
winter_home_schedule: "DON'T MISS THE OPENING!\r\n<br><br>\r\nEVERYDAY: Sauna after\
  \ dinner  and  jam till late late ;)\r\n"
winter_home_show: "With the help of our teachers and professional artists the show\
  \ is on! But the show is open for you to participate too!! We'd love you to be there\
  \ and share whatever skill you bring! <br> We will share invitations for the event\
  \ to the town of Arosa. Its a big event and we want to celebrate it with you all!\r\
  \n"
winter_home_specialevent: "On Thursday morning we will organize a snow event up on\
  \ the mountain of the Scuol ski resort (If the weather is good). <br>The transportation\
  \ to the station is a 20min drive. <br>  \U0001F642<br>Bring warm clothes for outdoor\
  \ acro. Free afternoon for ski, snowboard or free floor at the hall.<br><br>*As\
  \ an EXTRA, we could organize ski tickets for you, write us ;).\r\n"
winter_home_workshops: "There will be <b>3 acro workshops per \"acro\" day</b>. Expect\
  \ daily handstand, coaching, and other projects & jams throughout the day. <b>Longes\
  \ and mats will be available for continuous practice</b>.<br>\r\n<b>Skill Levels</b>:\r\
  \nNo beginner workshops — previous acro experience is required.\r\nWorkshops level\
  \ starts at intermediate with intro-level prerequisites for Flows, Icarians, or\
  \ Standing Acro.\r\n"
winter_prices_description: "Creating an Event like the Winter Acro is a real Orga\
  \ challenge in many ways - but we love the challenge - and we do all we can to keep\
  \ it as accessible as we can, while still offering all the goodies that make this\
  \ event special.\r\n<br>\r\n<strong> All tickets include: Accomodation & bedding,\
  \ food, workshops, wellness and snow days ticket.</strong> \r\n<br>\r\nSome tickets\
  \ go without accommodation but are limited.<br> There are no single day tickets\
  \ this year, we want everyone to have a full experience of the program we so carefully\
  \ organized.<br> <br>\r\n<strong>First round of booking confirmations:<br>\r\n10\
  \ December 2025</strong><br> <br>\r\n<strong>  Confirmation conditions:  </strong>\
  \ <br>\r\nYour spot is confirmed after payment. <br><br>\r\n    <b>Ticket Transfer</b>:\
  \ You can suggest a transfer of your ticket by email, it will strongly be considered\
  \ - specially in thigh schedule - but if there is a waiting list we keep the right\
  \ to give it preference.<br><br>\r\n\r\n<h2><b>1 CHF = 1€</b></h2><b>To make it\
  \ easier for our European friends please consider 1 CHF = 1€ </b><br>\r\n"
winter_prices_full: '6 Days Pass: CHF 730.- per Person in 3 pax Dorm'
winter_prices_full_nosleep: '6 Days Pass: CHF 500.- per Person <b>without</b> Accommodation'
winter_prices_refunds: "<strong>Cancellation Policy - In case <u>you</u> cancel.</strong><br>\r\
  \nIn case of cancellation, the following costs are charged: <br> \r\nUp to 30 days\
  \ prior to the event: CHF 90.- fixed cost <br>\r\n30 to 15 days prior to the event:\
  \  50% Festival Ticket <br>\r\n14 to 1 day(s) prior to the event: 100%  Festival\
  \ Ticket <br>\r\nOn the day of the Event or no-show:  100%  Festival Ticket<br><br>\
  \ \r\n\r\nIf you cannot join the event but have paid, consider the Ticket transfer\
  \ but let us know asap.<br><br>\r\n\r\n<strong>Cancellation Policy - In case <u>we</u>\
  \ cancel.</strong> <br>\r\nIf we have to cancel the Event there are different conditions\
  \ depending on your booking.<br>\r\n<strong> a)  </strong> without accommodation:\r\
  \nWe are going to <strong> make a full refund</strong>.<br>\r\n<strong> b) </strong>\
  \ with accommodation in Dorms: Fixed fee CHF 90.-  per Person (non-refundable) <br>\
  \ <br>"
winter_prices_short: '6 Days Pass: CHF 755.- per person in Double Room'
winter_prices_single: '6 Day Pass: CHF 705.- in 4 pax Dorm'
winter_prices_upgrade1: '6 Day Pass: CHF 680.- per person in 6 pax Dorm'
winter_prices_upgrade2: "<strong>No day passes available this year</strong><br><br>\r\
  \n<strong>Price reduction: </strong> <br>\r\n-You can apply to teach a Workshop\
  \ at the Festival (Payout: CHF 70.- per Teacher/Workshop)<br><br>\r\n"
winter_transportation_car: "<p>Once you arrive in Zürich, take the A3 motorway toward\
  \ Chur, then follow the A13 to Landquart. From there, continue on route 28 toward\
  \ Klosters, where you’ll load your car onto the Vereina car train for a quick ride\
  \ through the mountain tunnel to Sagliains in the Lower Engadin. After exiting the\
  \ tunnel, follow the road past Scuol and Strada, then take the mountain road up\
  \ to Tschlin. The journey offers spectacular alpine views and a touch of adventure.\
  \ In winter, check road and train conditions—snow chains or a 4x4 vehicle may be\
  \ required for the final ascent. The tranquil charm of Tschlin makes the trip unforgettable!</p>\r\
  \n"
winter_transportation_car_time: "<ul>\r\n<li>Berne – Arosa: 4h</li>\r\n<li>Basel –\
  \ Arosa: 4h</li>\r\n<li>Geneva – Arosa: 5h 30min</li>\r\n<li>Zurich – Tschlin: 3h</li>\r\
  \n</ul>\r\n"
winter_transportation_tickets: <p>Tickets can be bought in the Swiss Main Trains system,
  but it's worth to check other options.</p>
winter_transportation_train: "<p>\r\nThe picturesque destination Tschlin is nestled\
  \ in the Swiss Alps. To reach this charming spot, travelers from the Zürich can\
  \ follow the scenic train route through Switzerland (via Landquart, Scuol, and on\
  \ to Tschlin). </p>\r\n"
winter_transportation_train_time: "<ul>\r\n<li>Zurich – Landquart - Scuol - Tschlin:\
  \ 3h 20min</li>\r\n<li>Basel - Landquart - Scuol - Tschlin: 4h 20min</li>\r\n<li>Geneva\
  \ – Zürich – Landquart – Scuol - Tschlin: 6h 20min </li>\r\n<li>Berne – Zürich -\
  \ Landquart - Scuol - Tschlin: 4h 30min</li>\r\n</ul>\r\n"
